/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jzp_myapplication_JniUtils */

#ifndef _Included_com_jzp_myapplication_JniUtils
#define _Included_com_jzp_myapplication_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jzp_myapplication_JniUtils
 * Method:    getStringC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jzp_myapplication_JniUtils_getStringC
  (JNIEnv *, jclass);

/*
 * Class:     com_jzp_myapplication_JniUtils
 * Method:    myEncrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jzp_myapplication_JniUtils_myEncrypt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_jzp_myapplication_JniUtils
 * Method:    myDecrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jzp_myapplication_JniUtils_myDecrypt
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
