/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndk_SecurityJniUtils */

#ifndef _Included_com_ndk_SecurityJniUtils /* 防止com_ndk_SecurityJniUtils.h被重复引用 */
#define _Included_com_ndk_SecurityJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndk_SecurityJniUtils
 * Method:    getStringC
 * Signature: ()Ljava/lang/String; 表示函数的返回值是 java 的 String 对象。
 */
JNIEXPORT jstring JNICALL Java_com_ndk_SecurityJniUtils_getStringC
  (JNIEnv *, jclass);

/*
 * Class:     com_ndk_SecurityJniUtils
 * Method:    myEncrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ndk_SecurityJniUtils_myEncrypt
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ndk_SecurityJniUtils
 * Method:    myDecrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ndk_SecurityJniUtils_myDecrypt
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
