/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndk_NdkJniUtils */

#ifndef _Included_com_ndk_NdkJniUtils
#define _Included_com_ndk_NdkJniUtils
#ifdef __cplusplus
extern "C" {    /* 指定 C 调用约定 */
#endif
/*
 * Class:     com_ndk_NdkJniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 * JNIEnv* 和 jobject 是所有 jni 函数必有的两个参数，分别表示 jni 环境和对应的 java 类（或对象）本身）
 *  接口指针
 */
JNIEXPORT jstring JNICALL Java_com_ndk_NdkJniUtils_getCLanguageString(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
